"""add title to updates table

Revision ID: 20261007_0002
Revises: 20261007_0001
Create Date: 2026-10-07 13:58:12.192834
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20261007_0002'
down_revision: str | Sequence[str] | None = '20261007_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('title', sa.String(length=255), server_default='NULL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'title')
    # ### end Alembic commands ###