"""remove project id from updates table

Revision ID: 20261007_0001
Revises: 20261006_0001
Create Date: 2026-10-07 13:36:38.131783
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20261007_0001'
down_revision: str | Sequence[str] | None = '20261006_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('updates_project_id_fkey'), 'updates', type_='foreignkey')
    op.drop_column('updates', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('updates_project_id_fkey'), 'updates', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###